# Generated by Django 3.1.7 on 2021-03-27 03:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=12)),
                ('address', models.TextField(max_length=1000)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='petdate',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office_dates', to='vet.branchoffice'),
        ),
    ]
